version: "3.9"
services:
  postgres:
    container_name: database_api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=api_db
    image: postgres:14.3-alpine
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    image: server:latest
    links:
      - postgres
    env_file: .env
volumes:
  pgdata:
