version: "3.9"
services:
  postgres:
    container_name: database_api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=api_db
    image: postgres:14.3-alpine
    volumes:
      - ./sql/pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    image: server:latest
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=api_db
      - SERVER_CACHE_SIZE=128
volumes:
  pgdata:
