version: "3.9"
services:
  postgres:
    container_name: database_api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=api_db
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
